import logging
_logger = logging.getLogger(__name__)


import json
import secrets
import ast
from odoo.http import request, Response

_logger = logging.getLogger(__name__)

import werkzeug.utils
from odoo import http,api,models
from odoo.http import request
from odoo.addons import auth_signup
from odoo.exceptions import UserError
from odoo.addons.website.controllers.main import Website
from odoo.addons.web.controllers.utils import ensure_db
# import requests
import logging



class LSReviewUpdate(http.Controller):
    @http.route('/live/customer/review', type='json', auth='public', cors="*", website=True, csrf=False)
    def live_cust_review(self, **post):
        _logger.info("Executing live_cust_review...")
        try:
            vals = request.get_json_data()
        except Exception:
            vals = post
        try:
            live_record = request.env['ac.ars.live.streaming'].sudo().search([('name', '=', vals.get('token'))], limit=1)
            live_id = request.env['ac.ars.live.stream.token'].sudo().search([('token', '=', vals.get('token')),
                                                                      ('active', '=', False)], limit=1)
            if live_record and live_record.review:
                _logger.info("\n", live_record.review)
                if 'review' in vals or 'feedback' in vals:
                    live_record.sudo().write({'review': vals.get('review'), 'feedback': vals.get('feedback')})
                    live_id.send_live_stream_link(True, vals.get('review'), vals.get('feedback'))
                return {'update': True, 'review': live_record.review, 'feedback': live_record.feedback}
            elif live_record:
                if 'review' in vals or 'feedback' in vals:
                    live_record.sudo().write({'review': vals.get('review'), 'feedback': vals.get('feedback')})
                    live_id.send_live_stream_link(True, live_record.review, live_record.feedback)
                    return {'update': False, 'review': live_record.review, 'feedback': live_record.feedback}
                else:
                    return {'update': False, 'review': "0", 'feedback': ""}
            else:
                return {'update': False, 'review': "0", 'feedback': ""}
        except Exception as e:
            _logger.info(e)


class dms_login_integration(http.Controller):

    # @http.route(['/dms/token/customlogin'], type='http', auth='none', website=True)
    # def get_web_customlogin(self, **post):
    #     db = request.session.db
    #     request.session.logout(keep_db=True)
    #     user = post.get('login')
    #     users = user.replace("autochip", "@autochip")
    #     passwd = post.get('password')
    #     # passwd = 'a'
    #     base_url = request.env['ir.config_parameter'].sudo().get_param('web.base.url')
    #     url = "%s/web/session/authenticate" % base_url
    #     session_id = request.session.sid
    #     url = '/web/logins?csrf_token=%s&login=%s&password=%s&db=%s' % (session_id, users, passwd, db)
    #     return werkzeug.utils.redirect(url)
    @http.route(['/dms/token/custom/login'], type='http', auth='public', methods=['POST', 'OPTIONS'], cors="*",
                csrf=False)
    def map_and_generate_sso_token(self, **kw):
        if request.httprequest.method == 'OPTIONS':
            return Response(status=200)

        try:
            vals = request.httprequest.get_json(silent=True) or request.params
            if vals and 'params' in vals and isinstance(vals['params'], dict):
                vals = vals['params']
                
            user_id = vals.get('user_id')
            d_code = vals.get('d_code') or vals.get('d code')
            incoming_token = vals.get('token')  # Generated by the parent application

            if not user_id or not d_code or not incoming_token:
                return self._json_response({"status": 400, "message": "Missing required mapping fields"}, 400)

            company = request.env['res.company'].sudo().search([('dealer_code', '=', d_code)], limit=1)
            if not company:
                return self._json_response({"status": 404, "message": 'Dealer not found in LS'}, 404)

            # Check if user already exists based on mapping identifier (dms_uid)
            user = request.env['res.users'].sudo().search([('dms_uid', '=', user_id)], limit=1)

            if user:
                # Map the new incoming SSO token to the existing user
                update_vals = {
                    'dms_token': str(incoming_token),
                    'dms_auth_token': str(vals.get('auth_token', '')),
                    'company_id': company.id
                }
                if company.id not in user.company_ids.ids:
                    update_vals['company_ids'] = [(4, company.id)]
                user.sudo().write(update_vals)

            else:
                # Create user dynamically if they don't exist, mapped with a secure unguessable password
                user_name_raw = vals.get('user_name', 'User')
                user_name = ''.join(str(user_name_raw).split())
                login = f"{user_name}{user_id}".lower()

                usr_data = {
                    'name': user_name_raw,
                    'login': login,
                    'company_ids': [(4, company.id)],
                    'company_id': company.id,
                    'dms_uid': user_id,
                    'dms_token': str(incoming_token),
                    'password': secrets.token_urlsafe(32),  # Secure random placeholder password
                    'dms_auth_token': str(vals.get('auth_token', ''))
                }

                user = request.env['res.users'].sudo().create(usr_data)

                if user.partner_id:
                    email = f"{user_name.lower()}@automeet.in"
                    country = request.env['res.country'].sudo().search([('code', '=', 'IN')], limit=1)
                    user.partner_id.sudo().write({
                        'tz': 'Asia/Kolkata',
                        'email': email,
                        'country_id': country.id if country else False
                    })

                if hasattr(user, 'ls_set_user_permission'):
                    user.ls_set_user_permission()

            return self._json_response({"status": 200, "message": "Token mapped successfully"}, 200)

        except Exception as e:
            _logger.error("DMS Token Mapping Exception: %s", str(e))
            return self._json_response({"status": 500, "message": "Error, please contact Admin"}, 500)

    def _json_response(self, data, status=200):
        return Response(json.dumps(data), headers={'Content-Type': 'application/json'}, status=status)

    @http.route(['/dms/landing/redirect'], type='http', auth='public', website=True, s2s=False)
    def dms_landing_redirect(self, **kw):
        _logger.info("Executing dms_landing_redirect...")
        user_id = kw.get('uid')
        token = kw.get('token')
        
        # Ensure any old session is cleared (similar to Odoo 11 implementation)
        request.session.logout(keep_db=True)
        
        _logger.info("Landing redirect received uid: %s, token: %s", user_id, token)
        
        if not user_id or not token:
            _logger.warning("Missing uid or token in landing redirect.")
            return request.render('http_routing.404')
            
        user = request.env['res.users'].sudo().search([('dms_uid', '=', user_id), ('dms_token', '=', token)], limit=1)
        if not user:
            _logger.warning("No user found for dms_uid: %s and dms_token: %s. Token may be invalid or already consumed.", user_id, token)
            return request.render('http_routing.404')
            
        _logger.info("User %s successfully authenticated via SSO token.", user.login)
        # Securely login the user without password
        request.session.uid = user.id
        request.session.login = user.login
        request.session.session_token = user.sudo()._compute_session_token(request.session.sid)
        request.update_env(user=user.id)
        
        # --- NEW: Default App/Menu Selection (Live Streaming) ---
        action_xmlid = 'ac_ars_live_stream_dashboard.action_ac_ars_live_stream_dashboard'
        menu_xmlid = 'ac_ars_cc_camera.ac_ars_live_streaming_records'
        
        Action = request.env.ref(action_xmlid, raise_if_not_found=False)
        Menu = request.env.ref(menu_xmlid, raise_if_not_found=False)
        
        if Action and Menu:
            Action = Action.sudo()
            Menu = Menu.sudo()
            action_context = Action.context or '{}'
            try:
                ctx_dict = ast.literal_eval(action_context)
            except (ValueError, SyntaxError):
                ctx_dict = {}
                
            if ctx_dict.get('menu_id') != Menu.id:
                ctx_dict['menu_id'] = Menu.id
                Action.write({'context': str(ctx_dict)})
                
            user.sudo().write({'action_id': Action.id})
        # --------------------------------------------------------
        
        # Optional: Invalidate token after use for security (single-use token)
        # user.sudo().write({'dms_token': False})
        
        _logger.info("Redirecting user %s to Odoo backend.", user.login)
        return werkzeug.utils.redirect('/web')

    @http.route(
        '/dms/stream/customer/entry',
        type='json',
        auth='public',
        methods=['POST'],
        csrf=False,
        cors='*',
        website=True,
    )
    def dms_stream_customer_entry(self, **post):
        _logger.info("Executing dms_stream_customer_entry")

        try:
            vals = post or {}
            _logger.info("DMS customer entry payload: %s", vals)

            dealer_code = vals.get('d_code')
            enable = vals.get('enable')
            ro_no = vals.get('roRono')

            company = request.env['res.company'].sudo().search(
                [('dealer_code', '=', dealer_code)],
                limit=1,
            )

            if not company:
                return {
                    'status': 404,
                    'message': 'Dealer not found in LS',
                }

            if enable:
                request.env['res.partner'].sudo().create_customer(vals)

                return {
                    'status': 200,
                    'message': 'RO Created in LS',
                }

            data = request.env['ac.ars.allocation.data'].sudo().search(
                [('dms_ro_no', '=', ro_no)],
                limit=1,
                order='id desc',
            )

            if not data:
                return {
                    'status': 404,
                    'message': 'RO not found in LS',
                }

            if data.delete_allocation_data():
                data.unlink()

                return {
                    'status': 200,
                    'message': 'RO delete from LS',
                }

            return {
                'status': 500,
                'message': 'Not allow to deleted from LS',
            }

        except Exception:
            _logger.exception(
                "Error while processing DMS customer entry"
            )

            return {
                'status': 500,
                'message': 'Error while creating RO in LS',
            }

    @http.route(['/dms/dealer/status'], type='json', auth='public', methods=['POST'], cors="*", website=True,
                csrf=False)
    def dms_dealer_status(self, **post):
        _logger.info("Executing dms_dealer_status...")
        vals = post or {}
        try:
            dealer_code = None
            if 'dlrNo' in vals:
                dealer_code = vals.get('dlrNo')
                if dealer_code:
                    company_id = request.env['res.company'].sudo().search([('dealer_code', '=', dealer_code)],
                                                                          limit=1).id
                    if company_id:
                        return {"status": 200, "result": True, "message": 'Dealer found in LS'}
                    else:
                        return {"status": 404, "result": False, "message": 'Dealer not found in LS'}
                else:
                    return {"status": 404, "result": False, "message": 'Dealer not found in LS'}
            else:
                return {"status": 400, "result": False, "message": 'dlrNo is missing in request params'}
        except Exception as e:
            _logger.info("/n", e)
            return {"status": 500, "result": False, "message": 'Exception'}

    @http.route(['/dms/live/stream/stop'], type='json', auth='public', methods=['POST'], cors="*", website=True,
                csrf=False)
    def dms_live_stream_stop(self, **post):
        _logger.info("Executing dms_live_stream_stop...")
        vals = post or {}
        _logger.info("dms_live_stream_stop payload: %s", vals)
        result = {}
        try:
            if 'user_id' in vals and vals.get('user_id'):
                users = request.env['res.users'].sudo().search([('dms_uid', '=', vals.get('user_id'))], limit=1)
                if users:
                    allocation_id = request.env['allocation.data'].sudo().search(
                        [('dms_ro_no', '=', vals.get('roRono'))],
                        limit=1, order='id desc')
                    live_id = request.env['ac.ars.live.stream.token'].sudo().search([('dms_ro_number', '=', allocation_id.id)],
                                                                             limit=1, order='id desc')
                    if live_id and live_id.state == 'valid':
                        live_id.finish_live_stream()
                        result.update({'status': 200, "result": True, "message": 'Live stream stopped'})
                    else:
                        result.update({'status': 404, "result": False, "message": 'No valid live streaming Found'})
                    return result
            elif 'token' in vals and vals.get('token'):
                _logger.info("Searching for token: %s", vals.get('token'))
                live_id = request.env['ac.ars.live.stream.token'].sudo().search([('token', '=', vals.get('token'))],
                                                                         limit=1, order='id desc')
                _logger.info("Found live_id: %s, state: %s", live_id, live_id.state if live_id else 'None')
                if live_id and live_id.state == 'valid':
                    live_id.finish_live_stream()
                    result.update({'status': 200, "result": True, "message": 'Live stream stopped'})
                else:
                    result.update({'status': 404, "result": False, "message": 'No valid live streaming Found'})
                return result
            else:
                return {'status': 404, "result": False, "message": 'Authentication Error'}
        except Exception as e:
            _logger.info(e)
            return {'status': 404, "result": False, "message": 'Error'}

    @http.route(['/dms/live/stream/pause'], type='json', auth='public', methods=['POST'], cors="*", website=True,
                csrf=False)
    def dms_live_stream_pause(self, **post):
        _logger.info("Executing dms_live_stream_pause...")
        vals = post or {}
        result = {}
        try:
            users = request.env['res.users'].sudo().search([('dms_uid', '=', vals.get('user_id'))], limit=1)
            if users:
                allocation_id = request.env['allocation.data'].sudo().search([('dms_ro_no', '=', vals.get('roRono'))],
                                                                             limit=1, order='id desc')
                live_id = request.env['ac.ars.live.stream.token'].sudo().search([('dms_ro_number', '=', allocation_id.id)],
                                                                         limit=1, order='id desc')

                _logger.info("/dms/live/stream/pause", allocation_id, live_id)
                if live_id and live_id.state == 'valid':
                    if 'action' in vals and vals.get('action') == 'pause':
                        remark = vals.get('reason') if 'reason' in vals else ''
                        if live_id.ac_ars_live_streaming_pause('other', remark):
                            result.update({'status': 200, "result": True, "message": 'Live Stream Paused'})
                        else:
                            result.update({'status': 200, "result": False, "message": 'Unable to pause the streaming'})
                    elif 'action' in vals and vals.get('action') == 'resume':
                        if live_id.ac_ars_live_streaming_resume():
                            result.update({'status': 200, "result": True, "message": 'Live Stream Resumed'})
                        else:
                            result.update({'status': 200, "result": False, "message": 'Unable to resume the streaming'})
                else:
                    result.update({'status': 404, "result": False, "message": 'Error'})
                return result
            else:
                return {'status': 404, "result": False, "message": 'Authentication Error'}
        except Exception as e:
            _logger.info("/dms/live/stream/pause", e)
            return {'status': 404, "result": False, "message": 'Error'}


class rms_partner(models.Model):
    _inherit = 'res.partner'

    def get_partner(self, vals):
        if 'phone' in vals.keys():
            partner = self.search([('phone', '=', vals.get('phone'))], order="id desc", limit=1)
            if not partner:
                partner = self.create(vals)
            return partner
        elif 'email' in vals.keys():
            partner = self.search([('email', '=', vals.get('email'))], order="id desc", limit=1)
            if not partner:
                partner = self.create(vals)
            return partner
        else:
            partner = self.create(vals)
            return partner

    def get_model_details(self, vals):

        brand = vals.get('brand') if 'brand' in vals else False
        model = vals.get('model') if 'model' in vals else False
        model_variant = vals.get('varient') if 'varient' in vals else False
        uniq_id = vals.get('model_uniq') if 'model_uniq' in vals else False
        if model:
            model = model.split()
            car_model_id = self.env['product.template'].search([('name', 'ilike', model[0])])
            model_id = car_model_id if car_model_id else self.env.ref('rms_frontend.default_vehicle')
            mvariant_id = self.env['product.product'].search([('product_tmpl_id', '=', model_id.id)], limit=1).id
            return {'mvariant_id': mvariant_id, 'model_id': model_id.id}
        else:
            model_id = self.env.ref('rms_frontend.default_vehicle')
            mvariant_id = self.env['product.product'].search([('product_tmpl_id', '=', model_id.id)], limit=1).id
            return {'mvariant_id': mvariant_id, 'model_id': model_id.id}

    @api.model
    def create_customer(self, vals):
        print("hhhhhhhhhhhhhhhhh")
        print(vals)
        dealer_code = None
        if 'd_code' in vals:
            dealer_code = vals.get('d_code')
            company_id = self.env['res.company'].search([('dealer_code', '=', dealer_code)], limit=1).id
        else:
            company_id = self.env.company.id
        partner = {'name': vals.get('customer_name'), 'phone': vals.get('mobile'), 'email': vals.get('email')}
        part = self.get_partner(partner)
        # model_id = self.env.ref('rms_frontend.default_vehicle').id
        # mvariant_id = self.env['product.product'].search([('product_tmpl_id', '=', model_id)], limit=1).id

        allocation_data = {'dms_ro_no': vals.get('roRono'), 'partner_id': part.id,

                           'company_id': company_id, 'user_id': self.env.user.id}
        print(allocation_data,"ddddddddddddddssss")
        self.env['ac.ars.allocation.data'].create(allocation_data)
        # sale_data.update({'dms_ro_number': allocation_id.id})
        # so = self.env['sale.order'].create(sale_data)
        return True

    @api.returns('stock.warehouse', lambda value: value.id)
    def get_warehouse(self, d_code=None):
        """ Returns warehouse id of warehouse that contains location """
        if d_code is not None:
            company_id = self.env['res.company'].search([('dealer_code', '=', d_code)], limit=1).id
        else:
            company_id = self.env.company.id
        warehouse = self.env['stock.warehouse'].search([('company_id', '=', company_id)], limit=1)
        print(warehouse.name)
        return warehouse